data:
  data_location: ./audio_resynthesis/gavril_log
  extension: wav
model:
  block_size: 160
  hidden_size: 128
  n_bands: 65
  n_harmonic: 512
  sampling_rate: 16000
preprocess:
  block_size: 160
  oneshot: false
  out_dir: ./preprocessed/DDSP/resynth/gavril
  sampling_rate: 16000
  signal_length: 32000
train:
  overlap: 0.75
  scales:
  - 4096
  - 2048
  - 1024
  - 512
  - 256
  - 128
